### ISSUE TITLE
Appears to require ImageMagick 7+

### ISSUE THREAD

**Issue by itsthejb** [anomen-s/php-sane#3]
Hi there,

I was doing some work on my setup yesterday, and discovered that it appears the current configuration requires ImageMagick 7+, which isn't currently stated in the documentation. The reason is that [here](https://github.com/anomen-s/php-sane/blob/a2e0fbfbd2e83efcbb013b26b40fa3d1e329391a/incl/scan.php#L142-L148) the `convert` command-line assumes that JPEG compression is supported, and it appears this feature was added in 7+. It's possible to use less than 7, but would require detecting the version number and conditionally adding compression settings. However, since without compression this produces huge PDFs, I think it would be better to just require 7+. In my case, this required compiling from source (DietPi/Armbian), but no big deal to have a better result.

Also, it seems that `poppler-utils` also requires a newer version to support this, and I'm currently compiling those to get the same support.

So, I think just adding a note in the docs would be a good solution.

Thanks!

**Comment by anomen-s** [comment]
Hi,
which parameter are you missing? It works for me with 6.8 and since it's quite old code I doubt it would need imagemagick 7.

**Comment by itsthejb** [comment]
Hi there, 

Since I've now upgraded, hard to say. The problem I was having was perhaps only caused by pdfmerge. I would get empty PDFs. I ended up moving to PDFTK for that, so perhaps that was really the problem.

In any case, FYI at the least! Feel free to close this if you wish.
